eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
spring:
  application:
    name: client-consumer-feign
server:
  port: 8995
feign:
  hystrix:
    enabled: true